#!/bin/bash

dictFolder=~/.dict/
dictFile=~/.dict/dict.py

mkdir -p $dictFolder

cp dict.default dict
cp dict.py.default $dictFile

sed -i 's?PATH?'$dictFile'?' dict

echo Go to https://developer.oxforddictionaries.com to register Oxford application
echo -n "Enter APP ID > "
read appId
echo -n "Enter APP Key > "
read appKey

sed -i s/"oxford-app-id"/$appId/g $dictFile
sed -i s/"oxford-app-key"/$appKey/g $dictFile

echo "Move dict to /usr/local/bin"

# Use su if sudo isn't installed
root=sudo
$root --version &> /dev/null || root=su

case $root in
  sudo) sudo cp dict /usr/local/bin/ ;;
  su) su -c "cp dict /usr/local/bin/" ;;
esac

